config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  namespace :users do
    resource :notification_tokens, only: [:create]
  end

  resources :buddies, only: [:create, :index]
  resource :daily_statuses, only: [:show, :create]

  root to: 'home#show'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    if signed_in?
      UserBuddy.generate_visual_graph
      @users = User.all.where.not(id: current_user.id)
      @day = params[:day] || 1.day.from_now.to_date
      @attendancies = Attendancy.new(day: @day).compute
      @daily_status = current_user.daily_statuses.find_or_initialize_by(day: @day)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/show.html.slim
- if user_signed_in?
  | Logged in as #{current_user.email}
  - if @users.present?
    h3.text-xl.mt-10 Who are you buddies?
    = form_tag buddies_path, method: :post
      ul
        - @users.each do |user|
          li.block
            label
              = check_box_tag "buddies[]", user.id, current_user.buddies.include?(user), class: 'mr-2'
              = user.email
      = submit_tag "We're okay.", class: 'bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded mt-2'

  h3.text-xl.mt-10 Friendship graph
  = image_tag '/friendship.png'


  h3.text-xl.mt-10 Who is coming ?
  = form_tag root_path, method: :get, class: 'my-3'
    = date_field :day, nil, value: @day, class: 'border py-1 px-3 rounded'
    = submit_tag 'Show attendancy', class: 'bg-blue-500 hover:bg-blue-700 text-white py-1 px-3 ml-2 rounded'
  table.table-auto
    tr.border
      th email
      th answer
      th attendancy
    - User.all.each do |user|
      tr
        td.border.p-2 = user.email
        td.border.p-2
          - if current_user == user
            = form_for @daily_status, method: :post, url: daily_statuses_path,class: 'my-3' do |f|
              = f.hidden_field :day
              = f.select :answer, options_for_select(Attendancy::ALL, selected: @daily_status.answer), prompt: 'NOT ANSWERED'
              = f.submit 'save', class: 'ml-2 border p-1 rounded'
          - else
            = user.daily_statuses.find_by(day: 1.day.from_now)&.answer || 'NOT ANSWERED'
        td.border.p-2 = @attendancies[user.id]
- else
  = link_to 'login', new_user_session_path
  = link_to 'register', new_user_registration_path